parameters:
- name: test_dockerfile
  displayName: 'Dockerfile to use for testing once package is built.'
  type: string
  default: 'torch_ort/docker/Dockerfile.onnxruntime-torch2.0.0-cu118-cudnn8-devel-ubuntu20.04'

- name: upload_wheel
  displayName: 'Whether the wheel should be uploaded to Azure Storage'
  type: string
  default: 'yes'

stages:
- stage: Python_Packaging

  jobs:
    - job: Linux_py_GPU_Wheels
      timeoutInMinutes: 180
      workspace:
        clean: all
      pool: Onnxruntime-Linux-GPU
      strategy:
        matrix:
          Python3:
            PythonVersion: '3.9'

      variables:
        BuildType: 'nightly'
        UploadWheel: ${{ parameters.upload_wheel }}

      steps:
      - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
        displayName: 'Clean Agent Directories'
        condition: always()

      - checkout: self
        clean: true
        submodules: recursive

      - template: templates/packaging-pipeline-steps.yml
        parameters:
          PythonVersion: $(PythonVersion)
          PublicDockerFile: ${{ parameters.test_dockerfile }}
          UploadWheel: ${{ parameters.upload_wheel }}
          BuildType: $(BuildType)

      - template: templates/component-governance-component-detection-steps.yml
        parameters:
          condition: 'succeeded'
