stages:
- stage: Python_Packaging

  jobs:
    - job: Linux_py_GPU_Wheels
      timeoutInMinutes: 180
      workspace:
        clean: all
      pool: Onnxruntime-Linux-GPU
      strategy:
        matrix:
          Python38 Default onxruntime190 Cuda11.6:
            PythonVersion: '3.8'
            PublicDockerFile: 'torch_ort/docker/Dockerfile.ort-default-stable-torch1.12.1-onnxruntime190-cu116-cudnn8-devel-ubuntu18.04'
      variables:
        BuildType: 'stable'

      steps:
      - checkout: self
        clean: true
        submodules: recursive

      - template: templates/packaging-pipeline-steps.yml
        parameters:
          PythonVersion: $(PythonVersion)
          PublicDockerFile: $(PublicDockerFile)
          UploadWheel: $(UploadWheel)
          BuildType: $(BuildType)

      - template: templates/component-governance-component-detection-steps.yml
        parameters:
          condition: 'succeeded'

      - template: templates/clean-agent-build-directory-step.yml
