# TODO: Replace manual dispatch with push when ready
#on:
#  push:
on: 
  workflow_dispatch:
jobs:
  test_docker_image_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build a dockerfile
      run: docker build -f docker/Dockerfile.ort-torch190-onnxruntime181-cu102-cudnn7-devel-ubuntu18.04 -t torch-ort .
      id: build
    - name: Test
      run: docker run -t torch-ort python test/bert_for_sequence_classification.py
      id: test
